# Initialization

Test notebook for the damadics benchmark. Approach using anomaly detection techniques. 

First we import the necessary packages and create the global variables.

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import pandas as pd
import logging
import random
import plottingTools
import sys
import datetime
import graphviz 

sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')

from sklearn.covariance import EllipticEnvelope
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree
from sklearn.metrics import accuracy_score

from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns; sns.set(font_scale=1.2)

from ann_framework.data_handlers.data_handler_DAMADICS import DamadicsDataHandler

#Import the tunable model classes
from ann_framework.tunable_model.tunable_model import SequenceTunableModelClassification


#from IPython.display import display, HTML
%matplotlib notebook

## Setup some options for the test

In [ ]:
random_seed = 0 #Change this to make it really random, 0 for testing purposes
random.seed(random_seed)

y_trains = {'DummyClf':None, 'EllipticEnvelope':list(), 'MLP':None}
y_tests = {'DummyClf':None, 'EllipticEnvelope':list(), 'MLP':None}

pd.options.mode.chained_assignment = None
nsamples = 1000
scoringMetrics = ['precision_macro', 'recall_macro', 'f1_macro']
cv_folds = 4

# Create data hanlder and load the data

In [2]:
features = ['externalControllerOutput', 'undisturbedMediumFlow', 'pressureValveInlet', 
            'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow', 
           'selectedFault', 'faultType', 'faultIntensity']

selected_indices = np.array([1,3,4,5,6,7])
selected_features = list(features[i] for i in selected_indices-1)

#Does not work for sequence sizes larger than 1 given the way I'm generating the test data. 
#Need to properly define what the test data is going to be like.
window_size = 1
window_stride = 1

dHandlder_valve = DamadicsDataHandler(selected_features, window_size, window_stride, 
                                      binary_classes=True)
dHandlder_valve.connect_to_db('readOnly', '_readOnly2019', '169.236.181.40', 'damadics')

Connection to mysql+mysqldb://readOnly:_readOnly2019@169.236.181.40/damadics successfull


## Perform classification using sklearn

In [10]:
start_date = datetime.datetime(2018, 2, 14, 18, 59, 20)
time_delta = datetime.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=1, hours=0, weeks=0)
n = 250000
end_date = start_date + n*time_delta #get the first n instances

## Binary classification using decision tree (must get 95+% for this simple task)

tree_clf = tree.DecisionTreeClassifier()

tModel = SequenceTunableModelClassification('Damadics_Tree_SK', tree_clf, lib_type='scikit', data_handler=dHandlder_valve)
tModel.load_data(unroll=True, verbose=1, test_ratio=0.20, 
                 start_date=start_date, end_date=end_date)
tModel.print_data(print_top=True)


Loading data for the first time
Reloading data due to parameter change
Loading data for DAMADICS with window_size of 1, stride of 1. Cros-Validation ratio 0
Loading data from memory
Data Splitting: 0:00:00.000614
Printing shapes

Training data (X, y)
(205737, 6)
(205737, 1)
Testing data (X, y)
(250, 6)
(250, 1)
Printing first 5 elements

Training data (X, y)
[[3.66043e-01 8.49866e-01 6.49667e-01 2.13222e-01 9.99784e-01 0.00000e+00]
 [6.59356e-01 8.49437e-01 6.45173e-01 2.16581e-01 9.99018e-01 1.06700e-03]
 [6.59356e-01 8.50019e-01 6.50535e-01 2.12273e-01 9.98577e-01 0.00000e+00]
 [4.84302e-01 8.51305e-01 6.47092e-01 2.11460e-01 4.59894e-01 8.49068e-01]
 [7.32444e-01 8.49901e-01 6.48759e-01 2.12886e-01 1.00000e+00 9.19000e-04]]
[[-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]]
Testing data (X, y)
[[0.366043 0.84907  0.652659 0.214973 1.       0.001396]
 [0.366043 0.846921 0.642378 0.215928 0.999881 0.      ]
 [0.732444 0.849215 0.644677 0.215841 1.       0.      ]
 [0.257854 0.850184 0.646255 0.21656

In [11]:
tModel.train_model(verbose=1)

In [12]:
tModel.predict_model()
tModel.evaluate_model()

predicted = tModel.y_predicted
test = tModel.y_test
test = np.ravel(test)

print("On test set")
print(accuracy_score(test, predicted))

clf = tModel.model
y_train_pred = clf.predict(tModel.X_train)

train = tModel.y_train
train = np.ravel(train)

print("On train set")
print(accuracy_score(tModel.y_train, y_train_pred))

On test set
0.612
On train set
1.0


In [13]:
feature_names = features[:1] + features[2:7]
print(feature_names)

dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=feature_names,  
                                class_names=["normal", "fault"],  
                                filled=True, rounded=True, special_characters=True)  
graph = graphviz.Source(dot_data)  
#graph 

graph.render('decision_tree_damadics', view=True)  

['externalControllerOutput', 'pressureValveInlet', 'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow']


KeyboardInterrupt: 

# Generate some plots

We now generate some useful plots to gain some insight on the data.

In [ ]:
X = dHandlder_valve._X_train
n = X.shape[0]

n=6
plt.plot(np.arange(0,n), X[:6,1])
plt.show()

In [ ]:
jplot_vars = ['externalControllerOutput', 'disturbedMediumFlow', 'pressureValveInlet', 'pressureValveOutlet', 
              'mediumTemperature', 'rodDisplacement']

df_sp = df[['pressureValveInlet', 'pressureValveOutlet', 'selectedFault']]
plottingTools.scatterplot_fault(df_sp, "Normal vs Faulty observations", nsamples = 200)

df_jp = df
df_jp.loc[df_jp['selectedFault'] != 20, 'selectedFault'] = 1
df_jp.loc[df_jp['selectedFault'] == 20, 'selectedFault'] = 0

plottingTools.jp_plotData(df_jp, "Joint plot", hue='selectedFault', saveToFile='damadicsPairPlot.png', vars = jplot_vars)

In [ ]:
## Binary classification using decision tree (must get 95+% for this simple task)

#reformat labels using sklearn's decision tree format
y_train_binary = [-1 if int(y_train[0]) == 20 else 1 for y_train in dHandlder_valve._y_train]

tree_clf = tree.DecisionTreeClassifier(max_depth=6, min_samples_leaf=5)

tModel = SequenceTunableModelClassification('Damadics_Tree_SK', tree_clf, lib_type='scikit', data_handler=dHandlder_valve)
tModel

tree_clf.fit()


In [ ]:
dot_data = tree.export_graphviz(clf, out_file=None,
                                feature_names=iris.feature_names,  
                                class_names=iris.target_names,  
                                filled=True, rounded=True, special_characters=True)  
graph = graphviz.Source(dot_data)  
graph 

In [ ]:
#One hot encoding
#cat = np.arange(1,5)
#encoder = OneHotEncoder(categories=[cat])
#encoder = OneHotEncoder(categories=[[20]])
#output_one_hot_matrix = encoder.fit_transform(dHandlder_valve._y.reshape(-1, 1)).toarray()
#print(encoder.categories_)
#print(self._y[:5])
#print(output_one_hot_matrix[:5, :])
#output_one_hot_matrix = self.one_hot_encode(self._df.shape[0])
#output_one_hot_matrix = encoder.fit_transform(self._y.reshape(-1, 1)).toarray()
#self._y = encoder.fit_transform(self._y.reshape(-1, 1)).toarray()
#dHandlder_valve.print_data(print_top=True)

In [ ]:
y_train_elliptic = y_train
y_test_elliptic = y_test
y_train_elliptic[y_train_elliptic == 0] = -1
y_test_elliptic[y_test_elliptic == 0] = -1
y_trains['EllipticEnvelope'] = y_train_elliptic
y_tests['EllipticEnvelope'] = y_test_elliptic

logger.info('Performing cross validations')

#print(X_train.shape)
#print(y_train.shape)

for classifierKey in classifiers:
    
    print('\nResults for {} classifier'.format(classifierKey))
    
    clf = classifiers[classifierKey]
    
    if y_trains[classifierKey] is not None:
        y_train = y_trains[classifierKey]
        
    cv_scores = cross_validate(clf, X_train, y_train[:,0], scoring=scoringMetrics, cv=cv_folds, return_train_score=True)
        
    print('{}-fold cross validation'.format(cv_folds))
        
    for key in cv_scores:
        print("For metric %s Accuracy: %0.5f (+/- %0.5f)" % (key, cv_scores[key].mean(), cv_scores[key].std() * 2))
    #print('Total sample size {}, Train Size {}, Test Size {}'.format(X_raw.shape[0], X_train.shape[0], X_test.shape[0]))'''