# Initialization

Test notebook for the damadics benchmark. Generate some plots and perform basic statistical analysis

First we import the necessary packages and create the global variables.

In [12]:
import sys
import datetime
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch   # Used for reordering the correlation matrix

from matplotlib import rc

from scipy import stats

#sys.path.append('/Users/davidlaredorazo/Documents/University_of_California/Research/Projects')
sys.path.append('/media/controlslab/DATA/Projects')

from ann_framework.data_handlers.data_handler_DAMADICS import DamadicsDataHandler

#from IPython.display import display, HTML
%matplotlib notebook

## Load Data

In [2]:
start_date_test = datetime.datetime(2018, 2, 14, 18, 59, 20) # ValveReadingsTest, testing
start_date_training = datetime.datetime(2019, 6, 14, 17, 6, 41) # ValveReadings, trainning
time_delta = datetime.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=1, hours=0, weeks=0)

n = 200000

end_date_training = start_date_training + n*time_delta #get the first n instances
end_date_test = start_date_test + n*time_delta #get the first n instances

print(start_date_training)
print(end_date_training)

features = ['externalControllerOutput', 'undisturbedMediumFlow', 'pressureValveInlet', 
            'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow', 
           'selectedFault', 'faultType', 'faultIntensity']

selected_indices = np.array([1,3,4,5,6,7])
selected_features = list(features[i] for i in selected_indices-1)
print(selected_features)

window_size = 1
window_stride = 1

2019-06-14 17:06:41
2019-10-31 14:26:41
['externalControllerOutput', 'pressureValveInlet', 'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow']


In [3]:
dHandlder_valve = DamadicsDataHandler(selected_features, window_size, window_stride,
                                      start_date_training=start_date_training, end_date_training=end_date_training,
                                      start_date_test=start_date_test, end_date_test=end_date_test,
                                      binary_classes=True, one_hot_encode=False, samples_per_run=50)
dHandlder_valve.connect_to_db('readOnly', '_readOnly2019', '169.236.181.40', 'damadics')

Connection to mysql+mysqldb://readOnly:_readOnly2019@169.236.181.40/damadics successfull


In [4]:
dHandlder_valve.load_data(unroll=True, verbose=1, cross_validation_ratio=0.5, shuffle_samples=True)
dHandlder_valve.print_data(print_top=True)

Loading training data for DAMADICS with window_size of 1, stride of 1. Cros-Validation ratio 0.5
Loading data from database
Reading data from ValveReading
2019-06-14 17:06:41
2019-10-31 14:26:41
Extracting data from database runtime: 0:00:01.392976
Data Splitting: 0:00:00.000107
Loading test data for DAMADICS with window_size of 1, stride of 1
Loading data from database
Reading data from ValveReadingTest
Extracting data from database runtime: 0:00:01.256745
Printing shapes

Training data (X, y)
(102998, 6)
(102998, 1)
Cross-Validation data (X, y)
(3442, 6)
(3442, 1)
Testing data (X, y)
(7785, 6)
(7785, 1)
Printing first 5 elements

Training data (X, y)
[[0.484302 0.850783 0.655481 0.214468 0.467455 0.80473 ]
 [0.257854 0.851061 0.655758 0.21368  0.508822 0.654641]
 [0.257854 0.850269 0.641243 0.215054 0.46781  0.826894]
 [0.659356 0.849571 0.65667  0.212516 0.829297 0.131878]
 [0.366043 0.849401 0.653013 0.2137   0.676856 0.291002]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]
Cross-Validation 

In [5]:
cols = ['externalControllerOutput', 'pressureValveInlet', 'pressureValveOutlet', 'mediumTemperature', 
        'rodDisplacement', 'disturbedMediumFlow']

cols_fault = cols.copy()
cols_fault.append('Fault')

print(cols_fault)

df_training = pd.DataFrame(np.concatenate((dHandlder_valve.X_train, dHandlder_valve.y_train), axis=1), 
                          columns=cols_fault)

df_cv = pd.DataFrame(np.concatenate((dHandlder_valve.X_crossVal, dHandlder_valve.y_crossVal), axis=1), 
                     columns=cols_fault)

df_test = pd.DataFrame(np.concatenate((dHandlder_valve.X_test, dHandlder_valve.y_test), axis=1), 
                      columns=cols_fault)

['externalControllerOutput', 'pressureValveInlet', 'pressureValveOutlet', 'mediumTemperature', 'rodDisplacement', 'disturbedMediumFlow', 'Fault']


In [6]:
df_training.head()
#df_cv.head()
#df_test.head()

externalControllerOutput  pressureValveInlet  pressureValveOutlet  \
0                  0.484302            0.850783             0.655481   
1                  0.257854            0.851061             0.655758   
2                  0.257854            0.850269             0.641243   
3                  0.659356            0.849571             0.656670   
4                  0.366043            0.849401             0.653013   

   mediumTemperature  rodDisplacement  disturbedMediumFlow  Fault  
0           0.214468         0.467455             0.804730   -1.0  
1           0.213680         0.508822             0.654641   -1.0  
2           0.215054         0.467810             0.826894   -1.0  
3           0.212516         0.829297             0.131878   -1.0  
4           0.213700         0.676856             0.291002   -1.0

In [7]:
df_training_sub = df_training[:100]
df_training_sub.head()

externalControllerOutput  pressureValveInlet  pressureValveOutlet  \
0                  0.484302            0.850783             0.655481   
1                  0.257854            0.851061             0.655758   
2                  0.257854            0.850269             0.641243   
3                  0.659356            0.849571             0.656670   
4                  0.366043            0.849401             0.653013   

   mediumTemperature  rodDisplacement  disturbedMediumFlow  Fault  
0           0.214468         0.467455             0.804730   -1.0  
1           0.213680         0.508822             0.654641   -1.0  
2           0.215054         0.467810             0.826894   -1.0  
3           0.212516         0.829297             0.131878   -1.0  
4           0.213700         0.676856             0.291002   -1.0

In [8]:
df_training_sub.shape
df_training_sub.describe()

externalControllerOutput  pressureValveInlet  pressureValveOutlet  \
count                100.000000          100.000000           100.000000   
mean                   0.492104            0.849362             0.649872   
std                    0.174186            0.001362             0.004841   
min                    0.257854            0.845809             0.641186   
25%                    0.366043            0.848651             0.645177   
50%                    0.484302            0.849414             0.649653   
75%                    0.659356            0.850337             0.654268   
max                    0.732444            0.852504             0.658374   

       mediumTemperature  rodDisplacement  disturbedMediumFlow       Fault  
count         100.000000       100.000000           100.000000  100.000000  
mean            0.215207         0.601842             0.512930   -0.480000  
std             0.001437         0.154723             0.311699    0.881688  
min             0.210349         0.248678             0.128009   -1.000000  
25%             0.214389         0.465718             0.215404   -1.000000  
50%             0.215275         0.580485             0.486822   -1.000000  
75%             0.216168         0.734241             0.826707    1.000000  
max             0.218341         0.832933             1.000000    1.000000

In [9]:
jplot_vars = selected_features

g = sns.pairplot(df_training_sub, hue='Fault', vars=cols)
plt.savefig('pairplot_raw.pdf', format='pdf', pad_inches=0.5, bbox_inches='tight')

In [10]:
# Only select the requested columns
df_corr_matrix = df_training_sub[selected_features]

# This computes the Pearson coefficient for all couples
corr = df_corr_matrix.corr().fillna(0)

# Start drawing

# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
size = max(10, len(corr.columns)/2.)
f, ax = plt.subplots(figsize=(size, size))

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, square=True, linewidths=.5, cbar_kws={"shrink": 0.5}, ax=ax)

## Load data with time window

Here we use a time window and the mean values of the time window as features

In [ ]:
window_size = 10
window_stride = 1

dHandlder_valve_mean = DamadicsDataHandler(selected_features, window_size, window_stride,
                                      start_date_training=start_date_training, end_date_training=end_date_training,
                                      start_date_test=start_date_test, end_date_test=end_date_test,
                                      binary_classes=True, one_hot_encode=False, samples_per_run=50)
dHandlder_valve_mean.connect_to_db('readOnly', '_readOnly2019', '169.236.181.40', 'damadics')

In [ ]:
dHandlder_valve_mean.load_data(unroll=False, verbose=1, cross_validation_ratio=0.5, shuffle_samples=True)
dHandlder_valve_mean.print_data(print_top=True)

In [ ]:
cols = ['externalControllerOutput', 'pressureValveInlet', 'pressureValveOutlet', 'mediumTemperature', 
        'rodDisplacement', 'disturbedMediumFlow']

cols_fault = cols.copy()
cols_fault.append('Fault')

X_training = dHandlder_valve_mean.X_train
X_training = np.array([np.mean(time_window, axis=0) for time_window in X_training])

print(X_training)

X_crossVal = dHandlder_valve_mean.X_crossVal
X_crossVal = np.array([np.mean(time_window, axis=0) for time_window in X_crossVal])

X_test = dHandlder_valve_mean.X_test
X_test = np.array([np.mean(time_window, axis=0) for time_window in X_test])


df_training = pd.DataFrame(np.concatenate((X_training, dHandlder_valve_mean.y_train), axis=1), columns=cols_fault)
df_crossVal = pd.DataFrame(np.concatenate((X_crossVal, dHandlder_valve_mean.y_crossVal), axis=1), columns=cols_fault)
df_test = pd.DataFrame(np.concatenate((X_test, dHandlder_valve_mean.y_test), axis=1), columns=cols_fault)

In [ ]:
df_training_sub = df_training[:100]
df_training_sub.head()

In [ ]:
jplot_vars = selected_features

g = sns.pairplot(df_training_sub, hue='Fault', vars=cols)
plt.savefig('pairplot_mean.pdf', format='pdf', pad_inches=0.5, bbox_inches='tight')